name: yalo
description: Yalo (Yaml localizations) - is a package, which give you a simplest way to get localizations from yaml files
version: 2.0.1
homepage: https://github.com/alphamikle/yalo

environment:
  sdk: ">=2.14.2 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  dart_style: ^2.0.2
  yaml: ^3.1.0
  path: ^1.8.0
  analyzer: 2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: